mod host_setup;
mod create_map;
// mod join;
mod landing;
// mod lobby;
// mod seeker;
// mod hider;
// mod host;
// mod not_found;
mod game;

// pub use hider::HiderView;
// pub use host::HostView;
pub use host_setup::HostSetup;
pub use create_map::CreateMap;
// pub use join::JoinGame;
pub use landing::LandingPage;
// pub use lobby::Lobby;
// pub use not_found::NotFound;
// pub use seeker::SeekerView;
pub use game::GameView;
